# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.sepolia]
url = "https://api.cartridge.gg/x/starknet/sepolia"
accounts-file = "/home/newking/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "testnet-deployer"
wait-params = { timeout = 300, retry-interval = 10 }
show-explorer-links = true
